apiVersion: apps/v1
kind: Deployment
metadata:
  name: endava-coding-exercise-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endava-coding-exercise
  template:
    metadata:
      labels:
        app: endava-coding-exercise
    spec:
      containers:
        - name: endava-coding-exercise
          image: endava-coding-exercise:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
        - name: redis
          image: redis
          ports:
            - containerPort: 6379